/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package identificador_ip_web_cliente_menu_e_submenu;

import br.com.jmary.home.Home;
import br.com.jmary.utilidades.Exportando;
import br.com.jmary.utilidades.JOPM;
import br.com.jmary.utilidades.PopupMenu_Colar;
import brouser_java_fx.BrowserFX;
import java.awt.BorderLayout;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import identificador_ip_web_cliente.Ler_Email;

/**
 *
 * @author ana
 */
public class Identificador_Ip_Web_Cliente_Submenu_01 extends javax.swing.JPanel {
    
    Exportando Exportando;
    PopupMenu_Colar PopupMenu_Colar;
    Home Home;
        
    public Identificador_Ip_Web_Cliente_Submenu_01( Home Home2 ) {
        Home = Home2;
        
        initComponents();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel28 = new javax.swing.JPanel();
        JPOpcao_26 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        JPOpcao_27 = new javax.swing.JPanel();
        tf_ip_do_servidor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JPOpcao_30 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        JPOpcao_31 = new javax.swing.JPanel();
        tf_Senha = new javax.swing.JTextField();
        JPOpcao_32 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        JPOpcao_33 = new javax.swing.JPanel();
        tf_Email = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(894, 71));

        JPOpcao_26.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_26.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_26MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_26MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_26MousePressed(evt);
            }
        });

        jLabel80.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel80.setText("IP do Servidor.: ");

        javax.swing.GroupLayout JPOpcao_26Layout = new javax.swing.GroupLayout(JPOpcao_26);
        JPOpcao_26.setLayout(JPOpcao_26Layout);
        JPOpcao_26Layout.setHorizontalGroup(
            JPOpcao_26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel80, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
        );
        JPOpcao_26Layout.setVerticalGroup(
            JPOpcao_26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel80, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        JPOpcao_27.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_27.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_27MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_27MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_27MousePressed(evt);
            }
        });

        tf_ip_do_servidor.setEditable(false);
        tf_ip_do_servidor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tf_ip_do_servidor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tf_ip_do_servidor.setPreferredSize(new java.awt.Dimension(209, 25));
        tf_ip_do_servidor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_ip_do_servidorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf_ip_do_servidorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tf_ip_do_servidorMouseExited(evt);
            }
        });
        tf_ip_do_servidor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_ip_do_servidorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout JPOpcao_27Layout = new javax.swing.GroupLayout(JPOpcao_27);
        JPOpcao_27.setLayout(JPOpcao_27Layout);
        JPOpcao_27Layout.setHorizontalGroup(
            JPOpcao_27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_ip_do_servidor, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPOpcao_27Layout.setVerticalGroup(
            JPOpcao_27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_27Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tf_ip_do_servidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/nuvem.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel2.setText("Identificador de IP na Web - Cliente - JMarySystems");

        JPOpcao_30.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_30.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_30MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_30MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_30MousePressed(evt);
            }
        });

        jLabel82.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel82.setText("Senha.: ");

        javax.swing.GroupLayout JPOpcao_30Layout = new javax.swing.GroupLayout(JPOpcao_30);
        JPOpcao_30.setLayout(JPOpcao_30Layout);
        JPOpcao_30Layout.setHorizontalGroup(
            JPOpcao_30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel82, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
        );
        JPOpcao_30Layout.setVerticalGroup(
            JPOpcao_30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel82, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        JPOpcao_31.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_31.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_31.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_31MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_31MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_31MousePressed(evt);
            }
        });

        tf_Senha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tf_Senha.setText("********");
        tf_Senha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tf_Senha.setPreferredSize(new java.awt.Dimension(209, 25));
        tf_Senha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_SenhaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf_SenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tf_SenhaMouseExited(evt);
            }
        });
        tf_Senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_SenhaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout JPOpcao_31Layout = new javax.swing.GroupLayout(JPOpcao_31);
        JPOpcao_31.setLayout(JPOpcao_31Layout);
        JPOpcao_31Layout.setHorizontalGroup(
            JPOpcao_31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_Senha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPOpcao_31Layout.setVerticalGroup(
            JPOpcao_31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_31Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tf_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPOpcao_32.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_32.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_32MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_32MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_32MousePressed(evt);
            }
        });

        jLabel83.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel83.setText("Email.: ");

        javax.swing.GroupLayout JPOpcao_32Layout = new javax.swing.GroupLayout(JPOpcao_32);
        JPOpcao_32.setLayout(JPOpcao_32Layout);
        JPOpcao_32Layout.setHorizontalGroup(
            JPOpcao_32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPOpcao_32Layout.setVerticalGroup(
            JPOpcao_32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel83, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        JPOpcao_33.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_33.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_33.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_33MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_33MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_33MousePressed(evt);
            }
        });

        tf_Email.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tf_Email.setText("jmarysystems0001@gmail.com");
        tf_Email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tf_Email.setPreferredSize(new java.awt.Dimension(209, 25));
        tf_Email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_EmailMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf_EmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tf_EmailMouseExited(evt);
            }
        });
        tf_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_EmailKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout JPOpcao_33Layout = new javax.swing.GroupLayout(JPOpcao_33);
        JPOpcao_33.setLayout(JPOpcao_33Layout);
        JPOpcao_33Layout.setHorizontalGroup(
            JPOpcao_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_33Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPOpcao_33Layout.setVerticalGroup(
            JPOpcao_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_33Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tf_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(JPOpcao_26, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPOpcao_27, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPOpcao_32, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(JPOpcao_30, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPOpcao_33, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(JPOpcao_31, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JPOpcao_32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(JPOpcao_27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JPOpcao_26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JPOpcao_30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addComponent(JPOpcao_33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPOpcao_31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JPOpcao_26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_26MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_26MouseEntered

    private void JPOpcao_26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_26MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_26MouseExited

    private void JPOpcao_26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_26MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_26MousePressed

    private void tf_ip_do_servidorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_ip_do_servidorMouseClicked
        try{
            PopupMenu_Colar = new PopupMenu_Colar(tf_ip_do_servidor);
        } catch( Exception e ){}
    }//GEN-LAST:event_tf_ip_do_servidorMouseClicked

    private void tf_ip_do_servidorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_ip_do_servidorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ip_do_servidorMouseEntered

    private void tf_ip_do_servidorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_ip_do_servidorMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ip_do_servidorMouseExited

    private void tf_ip_do_servidorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_ip_do_servidorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ip_do_servidorKeyReleased

    private void JPOpcao_27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_27MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_27MouseEntered

    private void JPOpcao_27MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_27MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_27MouseExited

    private void JPOpcao_27MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_27MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_27MousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed

        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );  
            Exportando = new Exportando("ABRINDO...");
            Exportando.setVisible(true);Exportando.pbg.setMinimum(0);
            Exportando.pbg.setMaximum( 100 );
            Exportando.pbg.setValue( 50 );
            
            enviar_mensagem();
            
            Exportando.fechar();
        } catch( Exception e ){ e.printStackTrace(); } } }.start();
    }//GEN-LAST:event_jLabel1MousePressed

    private void JPOpcao_30MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_30MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_30MouseEntered

    private void JPOpcao_30MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_30MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_30MouseExited

    private void JPOpcao_30MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_30MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_30MousePressed

    private void tf_SenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_SenhaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_SenhaMouseClicked

    private void tf_SenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_SenhaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_SenhaMouseEntered

    private void tf_SenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_SenhaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_SenhaMouseExited

    private void tf_SenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_SenhaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_SenhaKeyReleased

    private void JPOpcao_31MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_31MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_31MouseEntered

    private void JPOpcao_31MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_31MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_31MouseExited

    private void JPOpcao_31MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_31MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_31MousePressed

    private void JPOpcao_32MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_32MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_32MouseEntered

    private void JPOpcao_32MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_32MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_32MouseExited

    private void JPOpcao_32MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_32MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_32MousePressed

    private void tf_EmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_EmailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EmailMouseClicked

    private void tf_EmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_EmailMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EmailMouseEntered

    private void tf_EmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_EmailMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EmailMouseExited

    private void tf_EmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_EmailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EmailKeyReleased

    private void JPOpcao_33MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_33MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_33MouseEntered

    private void JPOpcao_33MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_33MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_33MouseExited

    private void JPOpcao_33MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_33MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_33MousePressed
    
    public void enviar_mensagem(){        
        /*new Thread() {   @Override public void run() {*/ try { 

        String destinatario  = tf_Email.getText().trim();
        String assunto = "0123456789";
        String login   = tf_Email.getText().trim();
        String pass    = tf_Senha.getText().trim();
        
        List<String> list_cmd = new ArrayList();
        list_cmd.add(destinatario);                               //Destinatário "jmarysystems@gmail.com"
        list_cmd.add( pass );                                  //Senha //"subzero3463"
        list_cmd.add( login );                    //E-mail //"subzero3463.01@gmail.com"  -  "pretim21@gmail.com"
        list_cmd.add( "Cleilson Henrique de Araujo" );          //nome do remetente do email //"subzero3463.01"
        list_cmd.add( assunto ); 
        
        List<File> fileMails = new ArrayList<File>();                       //lista contendo os arquivos anexos
        String arquivo1 = "/anexos/CLEILSON_HENRIQUE_DE_ARAUJO" + ".pdf";
        fileMails.add(new File(arquivo1));

        Ler_Email Ler_Email = new Ler_Email( list_cmd, fileMails ); 
        System.out.println( "1 - ip_do_servidor - " + Ler_Email.ip_do_servidor );
        tf_ip_do_servidor.setText( Ler_Email.ip_do_servidor );
        
        JPanel p = new JPanel( new BorderLayout() );  
        BrowserFX BrowserFX;
        BrowserFX = new BrowserFX( Ler_Email.ip_do_servidor+":8080",true,true,true );
        p.add( BrowserFX, BorderLayout.CENTER );
        Home.adicionar_Tela_De_Trabalho("Cliente Web JM", p);
         
        } catch( Exception e ){ JOPM JOPM = new JOPM( "MÉTODO: " + "criar_mensagem_e_setar_remetentes()\n"
                    ,"\nErro ao tentar criar_mensagem_e_setar_remetentes" 
                    ,this.getClass().getName() ); 
        } //} }.start();                 
    }
                
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPOpcao_26;
    private javax.swing.JPanel JPOpcao_27;
    private javax.swing.JPanel JPOpcao_30;
    private javax.swing.JPanel JPOpcao_31;
    private javax.swing.JPanel JPOpcao_32;
    private javax.swing.JPanel JPOpcao_33;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JPanel jPanel28;
    public javax.swing.JTextField tf_Email;
    public javax.swing.JTextField tf_Senha;
    public javax.swing.JTextField tf_ip_do_servidor;
    // End of variables declaration//GEN-END:variables
    
}